# Generated by Django 2.2.6 on 2019-10-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dynamics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('value', models.BigIntegerField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='core.Indicators')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='core.Offices')),
            ],
            options={
                'ordering': ('month',),
            },
        ),
    ]
