# Generated by Django 2.2.6 on 2019-10-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dynamics',
            new_name='Dynamic',
        ),
        migrations.RenameModel(
            old_name='Indicators',
            new_name='Indicator',
        ),
        migrations.RenameModel(
            old_name='Offices',
            new_name='Office',
        ),
    ]
