# Generated by Django 2.2.6 on 2019-10-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
