# Generated by Django 2.2.6 on 2019-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_office_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
