# Generated by Django 2.2.6 on 2019-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191029_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
